export const dummyData = [
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Morning Run",
    distance: 10520.3,
    moving_time: 3965,
    elapsed_time: 4599,
    total_elevation_gain: 235.4,
    type: "Run",
    workout_type: null,
    id: 2983485199,
    external_id: "2020-01-05_10-31-29_d6e290be-c65c-4290-ba34-67b6fb92ecae.tcx",
    upload_id: 3179712374,
    start_date: "2020-01-05T08:55:08Z",
    start_date_local: "2020-01-05T09:55:08Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.680561, 11.946495],
    end_latlng: [57.681299, 11.945956],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.680561,
    start_longitude: 11.946495,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a2983485199",
      summary_polyline:
        "ov`_Jqh|gAJJNK|AaFr@sCVa@j@Nx@x@h@UfBwAd@qC@e@PoAh@aBXk@vB_Bd@iAf@uBfAyAd@sA~Bi@Xa@l@Yt@}@`AeBRw@dAwBlBoF`@{@r@{@VOzAoAdAiC\\g@d@?v@e@jCc@bAaA`ABnB_CPITFtAfAh@ELKFu@L_@hBQ`@{@Lo@h@m@Zu@TQzDg@r@[pAHRIlA_AZ_Ar@qAhBaCl@wAZUv@oBTOrACV_@b@UT_@dA]xAk@t@u@VMj@w@ZMP[jAOhBm@b@DVUR[fAYRJjCAbBw@bBFh@\\p@Fn@a@X_@b@Q`AmB|@Ah@Dj@z@Gm@Qc@c@Y]HOIq@f@oACqAeAo@As@Uo@}@a@UWgA?q@_@aAMu@y@o@oA@Ya@a@Qa@A}Ab@y@|BMjAK`@i@HQf@KLk@DS{@{@aAGgEKwA@{@LyAJY|BwCfDgCd@u@f@g@~CqBn@WLD\\[ZNRGPl@dAjAZRb@Br@]f@f@h@ZnAHb@Ib@a@n@K~@g@HM?YPQb@@NI`@LHMJw@r@l@VDd@d@l@HQ?KYQFc@Mm@k@QYMv@SM[JKOSIcCb@U`@OhAm@Pa@Is@E]?e@[}A`@YO_Ay@I_@Ck@b@IPYd@Sj@}@|@Kn@u@z@FlAaAvA?h@Nb@_@Xs@PM@HQToBC}Ar@aACk@r@w@H_@Zg@t@eAl@k@N_@\\UBa@Sy@J_B~@s@T{AdBSZmBjAyAjAmBtB[hAMhBDdEGhAMn@e@`@]v@e@j@_@J[Ao@g@_B\\c@EOEQi@ZfAn@`AFp@e@Ki@FGDUj@m@NCJFJ@NWVOd@SHQd@WR_AzBg@^[j@wBdCeCnD}@h@sB~BaAn@yA^aCLgAj@qB~Cg@bAs@`CWnAm@n@Qb@Cl@TnBCV_@Pu@x@mCh@u@d@u@@wAfDgBrAaAdA[l@eBdFq@lAUXu@~Ba@p@cAn@MRIXBj@KGeBBkAm@e@IYUsA?eAc@iAU_@]c@kAqAsA_@QsBE}@ZaAJiBjDc@^wGbBkAz@aA|Ac@nAMp@KnA?hCKnB@rAw@]bB|Ad@tAfB|B`EfG|AnBFZCjAYnAW`@OJw@aBMD",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3179712374",
    average_speed: 2.653,
    max_speed: 4.9,
    average_cadence: 82,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 101.8,
    elev_low: 19.5,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Padel",
    distance: 0,
    moving_time: 5400,
    elapsed_time: 5400,
    total_elevation_gain: 0,
    type: "Workout",
    id: 3014428943,
    external_id: null,
    upload_id: null,
    start_date: "2020-01-06T09:00:00Z",
    start_date_local: "2020-01-06T10:00:00Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3014428943",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: null,
    average_speed: 0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5856.7,
    moving_time: 1739,
    elapsed_time: 1805,
    total_elevation_gain: 26.7,
    type: "Run",
    workout_type: 0,
    id: 2995557887,
    external_id: "2020-01-09_12-12-25_bce55172-b12b-4e57-b196-cda5c37f05f3.tcx",
    upload_id: 3193358667,
    start_date: "2020-01-09T11:35:45Z",
    start_date_local: "2020-01-09T12:35:45Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.682452, 11.94773],
    end_latlng: [57.702657, 11.957017],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.682452,
    start_longitude: 11.94773,
    achievement_count: 2,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a2995557887",
      summary_polyline:
        "iba_Jip|gAo@iAKY[c@_@SIQc@QKICGGm@G_@Ec@Ok@Ii@Y]]cAm@i@GAEGSLE?SLE?w@e@_@Gc@{@[U[YGEMAGKMGOWSAODc@BCCESCCOHg@M]BE?OQQKSEO@OGa@dAIJWTYNMN]Vi@P_@Da@LM?c@EGE[o@_@SWSgBiBo@wAm@u@O]IIk@[OUGSGfDCdF@~DCJGDiCQi@_Aa@e@OKCIKsAKaEKKKCc@RWDKFM{@CGIGE@QTMCE?GHO^KGA@s@n@OTKCKBGCEEOe@CAq@BIHMXIJKBK?QJOBa@Ve@TE?EGISSGIDUBYVM@EBWZSNO@OSIEABMz@KZMHCCQRE?EEOg@GGSi@QOQEI@OFKCK?MEKDWVE?QaAKy@OFWAm@OQDEAW]_@Ie@_@]c@w@KSMK@CAQk@KK[BKHWAKF_@b@a@pAGHOHSREOi@wGG[KY]g@QK[OK?SKa@Im@UIEOSw@e@o@UqAuAM]Ge@YoAWy@QYEMK{@?y@Oa@",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3193358667",
    average_speed: 3.368,
    max_speed: 19.3,
    average_cadence: 85.4,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 36.6,
    elev_low: 6.1,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5346.2,
    moving_time: 1528,
    elapsed_time: 1592,
    total_elevation_gain: 68.3,
    type: "Run",
    workout_type: 0,
    id: 2998172546,
    external_id: "2020-01-10_11-19-50_3dae50a6-73ef-464a-8f23-b901143e7539.tcx",
    upload_id: 3196310589,
    start_date: "2020-01-10T10:45:09Z",
    start_date_local: "2020-01-10T11:45:09Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.702177, 11.955659],
    end_latlng: [57.703357, 11.956881],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.702177,
    start_longitude: 11.955659,
    achievement_count: 1,
    kudos_count: 3,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a2998172546",
      summary_polyline:
        "q}d_Jya~gABBJ?BNCVD^FRV^\\L`@Rh@JrAn@p@Pb@Xd@`@v@d@^VZFPLVJHATOH?t@f@XBhAh@VF\\P\\FZXP?NJPBPJZHXR^Pd@JP?ZHXB^XVBDBf@d@b@RR@\\K`@QLCJ?PDp@?z@STM^Kr@OTARBPETBNCvBk@LKVGh@HRC\\@\\LHCL?t@ZJ?ZPVHTJJBb@ATEZMb@[Vb@n@p@Jj@BbADRHNf@b@b@Nn@^fDjAVDd@En@KRIZITAtA[\\Gb@A\\Hb@?h@LRATBTHVNTFnAO\\DPDTPf@n@XTvAh@n@Xx@l@^j@HPVrAHz@BlBHj@HHl@X~@\\rAz@n@l@b@p@L^RjAPhCAb@Qt@GJOJ_@Na@Fw@ZeAr@WVi@p@YTI@MCIESYy@kB[[c@y@s@e@c@OKCIEm@qAy@k@o@u@o@oAe@o@MY]m@Q_@o@i@OSUc@Sw@EEYSg@eA}@sA[q@s@yBWa@o@yAe@y@c@m@g@]WU{@oAWe@MO}@Yc@Fu@MU?SDSJSDSJW@}@Ig@Mo@Yi@MaA@wAMM@i@J}@Aw@V_@V]F]Ls@Pq@RyARWLkAVm@XUFU?UOQUCBYy@MKU]OK]QW[u@u@k@]KCc@Fm@QQMWI_@Ec@QSAOGGAMDc@Kq@B_AES?_BeAQc@}@e@c@EO@[JeA?WE]Sa@GMSWi@kAcAg@{@CICoAG_@GSSYq@wACw@EKKSK@WIUQIAG@",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3196310589",
    average_speed: 3.499,
    max_speed: 7.8,
    average_cadence: 89,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 33.9,
    elev_low: 5.7,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Backintervall ",
    distance: 4438.9,
    moving_time: 1683,
    elapsed_time: 1905,
    total_elevation_gain: 52,
    type: "Run",
    workout_type: 3,
    id: 3008227092,
    external_id: "2020-01-13_18-07-14_d77bc84a-b7ea-4f2d-8153-8ca178a17012.tcx",
    upload_id: 3207544918,
    start_date: "2020-01-13T17:13:00Z",
    start_date_local: "2020-01-13T18:13:00Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715735, 12.004381],
    end_latlng: [57.716349, 12.004142],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715735,
    start_longitude: 12.004381,
    achievement_count: 1,
    kudos_count: 4,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3008227092",
      summary_polyline:
        "irg_JkrghAJWDY@oAEuA?uCBu@Fg@N[TSv@Iz@YZSLSL]HYDa@BcACkAUyA[oABuCCc@Gu@NiAFkAGkGD{@NcAr@yCTuBF[Tc@V]^[b@Sp@QXUXQx@gAXi@H[?i@GgAOy@e@oBa@qAu@oAQu@EEIEQ?UHy@j@aB~Aw@~@iB|Ag@f@i@p@a@`@QVy@dCGZMx@_@~AWbCWxA]n@EXEDUFMPMh@AV@l@Jx@XlE`@zIHr@F|AFj@Az@KdCErBDtA\\dC@bACR_@nAGn@DhAOt@?`AFRL@ZTPR@HPZMb@SHGHe@~ACDOHMd@OX_@XEH?\\Fb@Nn@Vp@DVAXKd@E^HONs@?EGSk@gBG[AOBKNUHQDYAOCGoA{@MQKYCUDiABKNGPANDHLJf@DJp@`AFD\\y@FCXARMNC@ECCSNSBIDGNKl@M^YVWv@YVGLBZJn@l@jBCZSv@@PFW?MJc@AKG[Yy@Mq@Ga@X}@He@OOk@Y]c@Oi@CQ@aABKNGT@TJFLNl@p@bADBHELa@HMBARAr@W?CAEC?ML[DOHe@pA[^Op@MPSRCHAJBTNz@`@jAHX?NSv@?XDg@Jg@?Is@eCC_@@UN]Jc@@UIQUGs@c@_@k@A[FoADKNGT@NJX~@n@|@^z@Vz@LdAHVj@r@RLH?VQTYHO@U@CD@N\\HJVMJ]HgAMiAKm@@e@Ae@Bo@Ec@QU_@U]?WIIIC@",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3207544918",
    average_speed: 2.637,
    max_speed: 4.2,
    average_cadence: 84.7,
    has_heartrate: true,
    average_heartrate: 151.7,
    max_heartrate: 181,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 42.1,
    elev_low: 19.3,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass",
    distance: 0,
    moving_time: 3600,
    elapsed_time: 3600,
    total_elevation_gain: 0,
    type: "Workout",
    id: 3014419631,
    external_id: null,
    upload_id: null,
    start_date: "2020-01-15T10:30:00Z",
    start_date_local: "2020-01-15T11:30:00Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3014419631",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: null,
    average_speed: 0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5260.6,
    moving_time: 1877,
    elapsed_time: 1917,
    total_elevation_gain: 62.4,
    type: "Run",
    workout_type: 0,
    id: 3016017940,
    external_id: "garmin_push_4443449174",
    upload_id: 3216245869,
    start_date: "2020-01-16T11:01:41Z",
    start_date_local: "2020-01-16T12:01:41Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.703189, 11.956856],
    end_latlng: [57.702796, 11.956848],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.703189,
    start_longitude: 11.956856,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3016017940",
      summary_polyline:
        "{ce_Jii~gAl@BPF`@h@Jp@Bh@j@|@l@l@Rp@Xj@d@^Vf@ZbA\\n@d@HjA`AD@BCP?VBj@NBNBFnA^j@BzAj@f@L`@PPPjAr@VHhABf@HP\\XVDAd@JXBjAVf@Np@\\h@DLAVKd@KdAKh@@d@OtA{@dBOrBo@jABvAj@`@CV@h@HTH\\RXh@d@RRFd@Bd@SZ?HHd@@h@J\\RH?r@Kn@AV\\LLxAlAb@V`@d@^j@d@Lf@?hAk@d@Mb@Kb@Ab@Dh@ClBf@dBPb@@f@LhCvBb@Vf@NbAt@b@`@Rf@R`AHfA@v@Hn@DL^RR?~@Zb@Vb@^bA|AVr@b@xBDl@BdAS`Aa@\\]L_@HgAf@c@ZaB`Bc@Xe@G_AwBKQw@}@wBeA]c@_A_B}@sAYs@_@o@Sw@]m@_@_@c@Ya@]k@sAQy@Sa@iAuAm@iBk@qB]o@USe@Ie@Be@Ee@S_AYk@[iAe@a@a@IeA?a@Ei@w@]c@Fi@Xg@?e@Uo@Aq@[y@QiBQiALiARk@\\g@Le@Dg@Lc@BmA^sBRg@Pc@Xe@@[Ic@YgA{@eAg@i@]u@Wi@Ea@YiAe@cA[YOe@Ce@Ui@?c@Qa@Ya@S]e@]OSOKQAQgBw@KCI?]Sc@Oe@Y_@QK@c@Q[]W}@q@iB]k@]}A]gA",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: true,
    upload_id_str: "3216245869",
    average_speed: 2.803,
    max_speed: 4.9,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 33.9,
    elev_low: 6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Afternoon Run",
    distance: 12442,
    moving_time: 4859,
    elapsed_time: 5065,
    total_elevation_gain: 220.3,
    type: "Run",
    workout_type: null,
    id: 3028999349,
    external_id: "2020-01-20_21-24-16_efe1a3f0-0f83-4c25-aa51-5c04ddcfc21a.tcx",
    upload_id: 3230766426,
    start_date: "2020-01-20T16:59:01Z",
    start_date_local: "2020-01-20T17:59:01Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715764, 12.004135],
    end_latlng: [57.715664, 12.004387],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715764,
    start_longitude: 12.004135,
    achievement_count: 2,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3028999349",
      summary_polyline:
        "org_JypghAX_@d@MnBeAv@w@fAkBPw@f@aBvA_Bn@]b@e@hDOfFn@hEc@`IIl@YXT\\t@dAX~BJpAWt@VhAAl@NvDdClA_AXi@`Bi@Tc@Ho@WwJ\\Y`@IJw@CgBo@}R@mEVgIDMLEz@HFg@@kANGz@B~DnCh@BnAqARu@R]LEh@\\RGxAyArAgCh@i@`Ak@nAlD`@dB`BnG@h@Gd@s@zB?z@J|@z@XZn@f@X`@?d@c@Pk@`Ac@l@mAZILSr@e@d@eC`@E\\q@v@El@g@bAWrCFv@Pl@OVSVa@`As@`@oAv@gAtAX\\Q|@m@l@q@`A|@PzALRrARn@OhAv@vBn@z@SJF^|@JFxDoAv@i@\\o@~@D~@Wp@N~BEVKhALr@YXYRe@h@Od@a@Xc@Ha@l@]^cADi@`@sBCmBHs@GeBRmCn@yA~CcE^w@fAKz@]|CkBzCyBd@Q|AElFqB^m@t@yBp@}CGWUKeBsCKu@?uBKwA]mAaAc@_@Ts@vAMv@ITiAjAmA|BIr@QRWRw@?s@O}@h@WASQMAw@h@YCo@qAYkBu@}CiA_G[cAa@eC}@iC_@{AqBcGi@g@m@[_BOk@^c@r@_@`ASDUx@oAbBcBvACtA}@`D?`AUnBcAr@[CcAd@c@Gu@p@EX_@r@Eb@YhAOVJdACzAs@J_AQ{@TkAc@iAHs@y@[Ly@dAGzAGp@w@`AKf@Pr@Z^rAVPNHf@?p@o@Au@VkAjAOFw@Kc@Dm@^{@tA_CTmCrAc@j@o@nAm@p@G^FjACXs@|@e@fAUPMC?]GMa@WK[@YOCc@b@U?Yd@wAhAQZ_@Eg@l@uAv@]Su@cAaAf@a@Gc@w@o@yB{AO{BbBkAvBOl@m@x@sArD]cA[gB_A{Kk@cEU{@OMq@zAS@y@qB[_@kA[Uc@s@a@_@_@SYs@?g@a@}@F}A`@aCIuBz@oCtAmCXoBz@wEz@y@b@kBzAORC^pAvLnAzIl@pChApD~A|FP~@ZpG~@rTGtIEh@uBb@eA`@{@Ki@P[ZkC\\gAYsBJaDSeDj@{Ar@gBrCs@fBa@f@u@n@wBpAsAb@",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3230766426",
    average_speed: 2.561,
    max_speed: 4.4,
    average_cadence: 81.4,
    has_heartrate: true,
    average_heartrate: 152.6,
    max_heartrate: 172,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 106.2,
    elev_low: 20.6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass",
    distance: 0,
    moving_time: 3282,
    elapsed_time: 3282,
    total_elevation_gain: 0,
    type: "Workout",
    id: 3033263269,
    external_id: "2020-01-22_11-56-17_cb09928f-2ef6-492b-94bf-6511fc01f665.tcx",
    upload_id: 3235545680,
    start_date: "2020-01-22T10:31:38Z",
    start_date_local: "2020-01-22T11:31:38Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 1,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3033263269",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: false,
    upload_id_str: "3235545680",
    average_speed: 0,
    max_speed: 0,
    has_heartrate: true,
    average_heartrate: 129.9,
    max_heartrate: 164,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5325.8,
    moving_time: 1547,
    elapsed_time: 1591,
    total_elevation_gain: 70.2,
    type: "Run",
    workout_type: 0,
    id: 3035957849,
    external_id: "2020-01-23_11-26-57_6e6a38f2-699a-4109-b694-c75bfb2b692a.tcx",
    upload_id: 3238543506,
    start_date: "2020-01-23T10:51:46Z",
    start_date_local: "2020-01-23T11:51:46Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.702779, 11.956963],
    end_latlng: [57.703143, 11.957088],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.702779,
    start_longitude: 11.956963,
    achievement_count: 3,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3035957849",
      summary_polyline:
        "iae_J_j~gAJJH\\JnAFZFFF@\\j@HDXh@Vv@H^JXNP\\R@BCDL@dBnANTd@\\JNVF\\B\\L\\VZf@HFN@TMJADBPR\\HNP^PN\\TDTJVD^VVBTH\\TVXf@HRA~@HT\\\\VdAJl@?XXPJ^HXVb@RNBTER?hAYZG^ANKl@I~A_@h@QX@\\KVOPAd@Kd@?\\Cb@KZ@JDH@l@EX?^H~@j@THd@Fh@ZNDH?TEPKRUPGF@^\\d@PHHAlA@VHTLP`Af@XRv@\\hA`@d@LxA?n@UrCs@|@Kr@Hf@P`@D^Rp@JvAFPARF^R\\Xv@r@bB`Al@d@b@b@\\j@Vp@Lx@?~@@TJ\\JLh@^`Bt@XRj@n@n@`A\\dAVzAJz@?`AG`@EPMRQLOHiAZe@Vs@n@{A`BSFGAOKc@m@q@uAQU{@w@i@[a@KW?IEOc@Ua@[g@w@}@S_@[s@Qk@[_@Sw@Wc@QQi@Yk@e@]e@Si@YyAs@kAUq@q@kCa@q@_@w@e@i@e@}@KI_@OSM{AuAS]O_@GAw@Jo@ZE?CAIOW[C?U]YKa@L_@Fs@I[Im@Ec@U[Gw@C_@BQCi@AqATcAd@]HW@}An@gAP]Lw@Fk@Lg@Rg@Lk@Fi@MMIOOYQa@c@q@Oe@Ug@QUMcBo@SEe@Ym@Wc@IQGy@Q_Ai@q@MECUWWGWM}@s@m@[QMKGe@IYKa@IYUaB{@QOWIg@c@KMc@{Aq@yAUm@Ia@?c@Uy@[a@UIOM]Q",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3238543506",
    average_speed: 3.443,
    max_speed: 5.3,
    average_cadence: 89.4,
    has_heartrate: true,
    average_heartrate: 166.4,
    max_heartrate: 182,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 33.9,
    elev_low: 6.1,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5313.6,
    moving_time: 1702,
    elapsed_time: 1796,
    total_elevation_gain: 66.7,
    type: "Run",
    workout_type: 0,
    id: 3038675813,
    external_id: "2020-01-24_11-31-39_2411e5f6-2217-4e31-a78c-8b333c629edd.tcx",
    upload_id: 3241570448,
    start_date: "2020-01-24T10:34:42Z",
    start_date_local: "2020-01-24T11:34:42Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.703206, 11.957193],
    end_latlng: [57.703119, 11.957178],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.703206,
    start_longitude: 11.957193,
    achievement_count: 1,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3038675813",
      summary_polyline:
        "_de_Jmk~gAb@V`@LBFAVFdAF\\Ph@hAhBZfA`@`@\\Rh@f@PHJPh@^NPb@VLLXH`@DDNLPVHN@BFAJBPJTZLLLLDJJD?FG\\AXBR\\XJ\\?PCf@Cd@F^Td@d@JBX@r@J\\LHLJ\\LJF@\\CTDbABJBNNJNZPHJZT^Nh@Ap@Il@Sl@GPGv@Kf@Q^U^Ij@GZCREr@Ib@MZ?`@BJCV@\\Ez@BbAP^X^JnAh@b@VN?XG|Ak@HBHNVDT\\FDv@At@NNAXZlAbA~@l@f@t@RHJ?l@If@Bb@SPAx@Yx@BTCN@r@P`@DrA\\t@Bd@Ef@Lr@d@z@t@bB`Az@t@f@t@X`AJl@FbBF^DJ\\Tj@TZVr@^f@\\XZn@~@\\~@TnAHt@FdAAn@Ib@MZGHYPm@RWDq@`@kA`Ag@j@c@ZIBWBOIi@{@c@eAa@a@QWe@g@YQUISASGGEKYOU}AqB_@m@]}@]o@Ie@KOc@_@a@Me@W]_@]u@_AyCi@{@_@s@c@aAq@yBk@eAIEeBOOEkAc@w@e@o@S[QU[K_@CSCgAAE]WGOMCIBm@^_ABm@MYKKWKIi@EcAE[IU?ULW?SFc@D[P[F_@Tk@D_A^UNs@No@Pc@DSAiAR_@HkA^O?MCKEa@]QWQSMCSAWGSSm@[]g@aC}@o@g@WIYE{@YUEe@Y_@Gw@@y@U{@g@m@g@UW{@a@WGOAa@K]S]EeAm@i@o@]WIKM{@Uu@sA}CGc@a@}@Ig@UQUG",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3241570448",
    average_speed: 3.122,
    max_speed: 8.8,
    average_cadence: 85.9,
    has_heartrate: true,
    average_heartrate: 152.6,
    max_heartrate: 168,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 33.9,
    elev_low: 6.1,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Evening Run",
    distance: 11318.9,
    moving_time: 4186,
    elapsed_time: 5469,
    total_elevation_gain: 203.4,
    type: "Run",
    workout_type: 2,
    id: 3048575688,
    external_id: "7A32B1E0-FC24-4113-BB24-FA7A487E44EC",
    upload_id: 3252635560,
    start_date: "2020-01-27T17:04:13Z",
    start_date_local: "2020-01-27T18:04:13Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715729, 12.004997],
    end_latlng: [57.715542, 12.004478],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715729,
    start_longitude: 12.004997,
    achievement_count: 1,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 3,
    photo_count: 0,
    map: {
      id: "a3048575688",
      summary_polyline:
        "grg_JevghAHmBCwDZ{AdA}@vBs@T]Jg@AoBw@uEHkBMeCXeDI_EDwAR{Ab@qAf@{Cr@gBl@i@lBm@bAcAb@aA@sAU{BaAgDqAkC@u@RQp@aBZYl@kAnC{IdAkCjAyBfAe@DYE{BDu@f@l@fGX~H{@zEUx@Ul@k@n@YxC[vCQxDl@fCbCjAxCx@vCx@xEHvCXxERnB^bBXdCn@zCZbAf@n@PDrBkB|AaDd@o@bAa@b@?d@k@^kAXaCpAmETuA?c@Ky@W{@Gy@B_BX_@Hy@K}Fg@eDYa@?_@?Ov@gBXS|@oBlA]`@q@x@}@Tl@~@G`CeBT@z@}@~AcAn@o@V}@l@U`@]dACJSB[OwBQe@bAaCV]f@G^Yj@N~@Qf@k@PaAx@_B`@aBRUd@wAXc@fEcAVURo@FqCMoAc@mA_BgBQuDe@UUa@PS?u@GWa@q@_@UkB]k@}AN}@M_AU[Qk@AcCt@cDfBsBViBn@eB@q@J_@p@qALgBNkAt@aDnBaD|BsBA_AWe@g@eBeAa@s@}A[FU^}@F]^s@Ra@Vc@r@ICq@^YTSTM^WLq@Jc@`A_@DKTiAp@]j@GjAULm@rB?fBLl@EzBc@vA]|@E^y@{@s@Ri@OYN[x@k@nCe@xAKl@Sd@?\\Tp@VxB[lA]VYr@WfFAdBNjBb@tCs@dA}@d@Qf@IdAJ|BZdCXhFZ`BXj@QlA]Sy@FUMg@PkAC{AtAc@z@e@T[f@{Ap@m@?]Pc@Qs@`@OZM?MRSRc@Ta@|@i@hBYVQzAYNK`@Y\\c@FUp@a@XBn@_@vBSBk@]}@qBk@Gi@Js@rBg@~@mBV[Mk@g@g@SSYO_BA_BK_@o@w@w@}AoAW_@}@{ARyBt@i@k@a@Ok@EcC\\wAQqAq@WNoBhFa@d@g@Nq@Gg@a@mA@MD{@fAc@TGNObDKtHJ~IHlA`@xBNzAnAnJ|@bGXrCPr@?x@JbAxA|F`BlEf@dChBlY?pFGbAWb@Q|AOX_Dr@y@CuDhA_@Ig@q@uAJe@_@mBr@QAMa@c@AiAh@i@k@gAf@[?aApAi@XSZS^QfAc@bAk@j@wBpAq@fAi@b@",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3252635560",
    average_speed: 2.704,
    max_speed: 5.6,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 98.1,
    elev_low: 20.6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 6470.4,
    moving_time: 2020,
    elapsed_time: 2024,
    total_elevation_gain: 111,
    type: "Run",
    workout_type: 0,
    id: 3050403770,
    external_id: "2020-01-28_12-07-02_6c02dc62-8e8e-4efc-8325-639bbd40a829.tcx",
    upload_id: 3254730467,
    start_date: "2020-01-28T11:17:31Z",
    start_date_local: "2020-01-28T12:17:31Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.703112, 11.957161],
    end_latlng: [57.703053, 11.956946],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.703112,
    start_longitude: 11.957161,
    achievement_count: 3,
    kudos_count: 3,
    comment_count: 6,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3050403770",
      summary_polyline:
        "mce_Jgk~gAVLTPFJT`An@lATz@T\\Zp@Jd@HNvAbAt@T\\TVJ`@Tz@p@`@p@XXh@Vz@?VLd@NX@JBh@d@PFXBZZVFNLPF`@ZRVnATpAn@b@EXDPATZf@b@HDf@@LBz@Zp@@`ACf@GVOb@GVAd@Ml@IVM\\GN@FCFKDCt@KXMvAAn@E\\Q~ABn@PNHZENBZLVXz@RRPPJHATIN?VENBHPL`BDN\\\\xAp@hBp@dAZp@Az@Ql@[`BOTIf@G`@?l@Bh@NbAFh@HZHx@Ef@Xv@t@~@r@PR`Ad@PRh@\\XZ`@t@Tt@Lt@DdAF\\JTf@j@VLb@JjAp@j@p@d@p@Xx@Lj@RlBD~@Mn@Ub@]TkBl@c@ZkAxAsAnASf@Up@Ef@TfGI`EOnA{@|DEl@M|@UpCEz@Iv@IhEGfA[fA]x@KLUL[Fi@C{@[e@?o@F]?s@BQCOGs@q@o@_@a@[iAi@iAkA_@q@a@mBKSk@i@OY]iA]q@k@Y{@I{@WQQMSEYA_@Do@?qADqAZkBTw@j@eCP{@PoBFaEJsCJg@t@kAL]Jy@?eACYSgAOm@Ii@K]KQUQOEg@EIGMgAU_ACUGMEC_@?q@Ia@CKGGOCSAi@MgAYy@OcA]_BBqAEaA@w@FaAGi@IWOQ]Sc@i@WUYCo@YIAQ?SEODO?KUQFoAXs@^cAVSBIFWHu@f@OFYDOFo@PM?UISB_A\\a@HiA`@S?_Ac@YQ_AcAcA_AYOoBs@kBi@aAa@[GWKaAYc@Ga@Ac@IOG[a@UOi@i@c@Ga@Ck@]W[Q@a@Gc@QgAaAc@k@Ka@Sk@Y_Bc@cBKgAMw@CEGAk@EM?QB",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3254730467",
    average_speed: 3.203,
    max_speed: 6.6,
    average_cadence: 87.3,
    has_heartrate: true,
    average_heartrate: 159.2,
    max_heartrate: 182,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 60.4,
    elev_low: 6.1,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass",
    distance: 0,
    moving_time: 3300,
    elapsed_time: 3300,
    total_elevation_gain: 0,
    type: "Workout",
    id: 3053714863,
    external_id: null,
    upload_id: null,
    start_date: "2020-01-29T10:30:00Z",
    start_date_local: "2020-01-29T11:30:00Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3053714863",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: null,
    average_speed: 0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Morning Run",
    distance: 6315.7,
    moving_time: 2066,
    elapsed_time: 2159,
    total_elevation_gain: 120.8,
    type: "Run",
    workout_type: 0,
    id: 3058755081,
    external_id: "2020-01-31_10-48-54_38f6208d-af92-4871-8a38-ae8fdad9983b.tcx",
    upload_id: 3264240074,
    start_date: "2020-01-31T09:53:52Z",
    start_date_local: "2020-01-31T10:53:52Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.701913, 11.955414],
    end_latlng: [57.703298, 11.957234],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.701913,
    start_longitude: 11.955414,
    achievement_count: 1,
    kudos_count: 2,
    comment_count: 1,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3058755081",
      summary_polyline:
        "}{d_Ji`~gAr@nA`@Zj@TNJ?H^\\HXNTJDDAFILBR\\TRHNVTd@PP?THL?ZGD@FFJTRBb@PL@n@XHJXF^PPRRJ~@LTHj@l@ZRn@Fb@G`@Bl@z@NFJLTN`@Lv@Hb@Q`BMj@Yj@QZCTG^E\\Kb@@RG`@OTCXGT@n@Ed@F\\K`@?VBd@NPML?TDH?CBBB|AnA`@D`ACl@Bb@OPARLRBDJHl@Ab@BLVXj@XnBn@l@Xn@LTHV@ZEd@Q\\@dBWf@M`@Qd@EVD\\CL@\\N~@Xr@Jl@?ZC\\BHDXPrAlAb@Z`@Nh@Vx@l@f@d@Td@Ln@PjAHvBDNHFx@Xz@\\j@\\PPZb@j@~@P\\Lj@^|BDt@Ah@O~@_@`@IFq@No@Vs@f@o@j@e@l@g@^a@h@KTM|@?ZDrEDh@?p@BX?r@W|DG`@Sf@Q`A}@xDMp@e@nFAnA@nAE~@c@dBUd@SRe@Ac@Qw@QwBAUCk@AYEQGi@[a@]m@a@eB{Ak@u@IIw@qCgAwAUg@Yw@Ye@_@[q@Cg@Mi@m@GYEe@@i@As@@qAJs@n@iBN{@H}@NeAFy@EuAUiDYaAYm@SUOGaAAk@S]@aAZM?a@Ok@Gy@Ei@BSJQXQ`@Gb@O`@Ak@Hm@COMAw@Lc@@YCWBWFGAm@{AUgA?]D_@BaAC_@K[BIAg@@UCa@EQBw@FEBKCg@K[MEK?m@LQAGGKc@Ei@GIMA{@QW?YCK@]Go@Um@MK?WFK?SGIMMq@IcB@eCJgA@_@EqB@sAC_@EY?g@EMOIQC]Qk@w@c@{@MKWIc@Sm@IWWWOk@Uy@W_@Cg@a@k@Ge@Di@Kq@a@q@s@WMg@[gAWYMOASUQKi@Mk@Wm@i@c@e@GMYeAk@wAWe@IYOeAg@{@Mc@QSa@K",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3264240074",
    average_speed: 3.057,
    max_speed: 13,
    average_cadence: 85.3,
    has_heartrate: true,
    average_heartrate: 157.7,
    max_heartrate: 195,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 70.4,
    elev_low: 6.1,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Evening Run",
    distance: 14050.9,
    moving_time: 5298,
    elapsed_time: 5718,
    total_elevation_gain: 243,
    type: "Run",
    workout_type: 0,
    id: 3068861441,
    external_id: "2020-02-03_19-02-12_5e9af7b9-165e-4f7a-8e34-89348288f25b.tcx",
    upload_id: 3275567570,
    start_date: "2020-02-03T17:12:45Z",
    start_date_local: "2020-02-03T18:12:45Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715607, 12.004287],
    end_latlng: [57.716323, 12.004037],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715607,
    start_longitude: 12.004287,
    achievement_count: 1,
    kudos_count: 4,
    comment_count: 1,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3068861441",
      summary_polyline:
        "oqg_JwqghAHmAGmFJkDZg@rCaAVk@NaAOmEIe@]iAP{BGoBPkAHkBKoELoBh@wBp@mEt@_AvAo@`A}@p@gAPq@EwDU{A[uAgAoBIe@@m@d@m@t@iBpDgLzA}D`@m@fAe@\\c@NuCOQCWEwJLaK^]RFh@WAIn@K~@_BbAu@r@UrDIzAi@x@k@zAcBb@}@l@_BHaAA}BaAqJ[yJ@eBSgDUsCi@iCSiBOcGO}@@i@YsDA}CLcEKmAi@kBMkEe@kBqA_DqAmA}@[_Ay@a@{@ScABq@h@cED{AC{B_@kDFmCQiB@sAJ{AZqA@kANw@ZQzAdA|@XxAS`@]Vq@hB{BnAeCu@_@mBqBu@r@i@Ok@{@yBiBaBiBUy@FgBEo@}B_H?g@PmATi@x@\\`DD~@mAjAeDbAeBxDqDlAK`CbAbA_DrA_CHg@s@qAqAw@mAgDImAHYlA{Af@KH[POVcAB_AAh@BUl@Sd@i@f@O~Bj@hAMlCuAz@b@dAJfFo@n@_@v@Kt@gAXiA\\_@PBFnAJ`@bDXhBmAjAmA`@u@~AkBtBOx@i@tBRZT|ARhAK|C?|@\\r@|@x@b@bEd@dA_Aj@kBdAAv@g@|BURQ^TZMJSf@JdA[T^R@dAk@VRZ{@|@s@h@_AXgAN?Z~@DpCRzDj@bAb@FZTVb@H~C\\hAJpA?dAQxA?z@_@hEKtCDlIR`Dp@hTErB]dCWn@_AvA_@fAg@p@aFZiDtAm@`A{AhFqBfFcApHsApDSdC?~AJ`ABtBWh@uAp@s@`AyB`@}A~@Wh@k@h@u@lA}@b@k@rAy@@s@P_BpAoA`BWx@k@r@gAl@_@`@o@bAGb@UZg@zAW^WnAe@t@KnAA`BMn@}B~C_AjAcElCuAfB{@z@mCf@}@n@yAjDu@lABbAI`@}Ax@w@dAkA|@}AJi@j@{CjJaAdFs@vE]pCm@E{BtD{ApAwCxAwBxEc@l@w@f@uAvC{@n@g@A]ZI`@y@hBDnKCnAi@p@}@p@k@x@{DzJaAfDyAtDCbAjAdDXnAh@hD?p@e@zA_@p@cCdAk@h@m@bAu@fEy@lCKbCL|DEtAQfAJjBIlCn@pDJfAAlAa@tA}ChAi@z@SrBBhDNhCKxAm@x@kAU",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3275567570",
    average_speed: 2.652,
    max_speed: 4.9,
    average_cadence: 82,
    has_heartrate: true,
    average_heartrate: 151,
    max_heartrate: 174,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 128.2,
    elev_low: 20.7,
    pr_count: 1,
    total_photo_count: 1,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass",
    distance: 0,
    moving_time: 2818,
    elapsed_time: 2818,
    total_elevation_gain: 0,
    type: "WeightTraining",
    id: 3078711351,
    external_id: "2020-02-07_07-31-42_f7a3c184-b03d-401c-9f22-68b118a70f93.tcx",
    upload_id: 3286527797,
    start_date: "2020-02-06T15:30:57Z",
    start_date_local: "2020-02-06T16:30:57Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3078711351",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: false,
    upload_id_str: "3286527797",
    average_speed: 0,
    max_speed: 0,
    has_heartrate: true,
    average_heartrate: 135.9,
    max_heartrate: 163,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Morning Run",
    distance: 8430.7,
    moving_time: 2682,
    elapsed_time: 2692,
    total_elevation_gain: 140.3,
    type: "Run",
    workout_type: 0,
    id: 3081237136,
    external_id: "2020-02-08_08-15-57_c8a02a79-b8e3-4e32-a426-1578aea19bee.tcx",
    upload_id: 3289349210,
    start_date: "2020-02-08T07:19:08Z",
    start_date_local: "2020-02-08T08:19:08Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715634, 12.004595],
    end_latlng: [57.716229, 12.004207],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715634,
    start_longitude: 12.004595,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3081237136",
      summary_polyline:
        "uqg_JusghA@a@EkC@}@C{A@g@Fu@P_@`@Yl@Wp@IXKVYLYPcADuA?WU_CU_A@gCAg@KgANoBBe@Aq@IuCAs@HcANaAp@yCVkBNo@N]T]TSp@If@Yh@e@p@w@^w@Jg@@WCqAKqAOy@W{@a@aAq@oAA}AJgAPg@No@RUFKvEcOp@{ALm@BGJGl@IHMHe@HuAGsADsC?u@Ce@Dm@EcBDi@@qB?qBG_BJ_AFiBI_BAo@BSHWf@a@VG\\D`@EZDb@Ll@T^VZJTRb@Nh@JVLv@Vb@BPCN?r@GNGhAu@PUd@]LM^q@l@aBZ}ADa@C}CGeAIw@C{@WeD?k@O_DI{COuACmCC]Ia@E}@MgAS{BW_BI}CIe@?g@IsAGg@Ei@?gASiBQiCAm@DkA?oBEs@MaA?sAGcBM{@kAiDIc@Q]IW]e@q@g@w@[o@OIESSSYEOWuBAQF_BRuBDeAEoAMmA@m@Ek@D{@BeAEmAIgAM_AKcBEwAFu@Ji@DEHCPANBRJx@t@x@^p@Ph@j@LHR@b@U^IPAf@Hh@AL@JD\\@NDRLFHv@tAf@\\V\\l@bBx@xANfATnDZ|Ad@dAhBxBf@^NRb@vAZjAFr@A`BBt@VrBJpB?zCAzAENU`@iAnAo@Zy@D_@JWTYNcA|@e@x@Qp@Gb@Ez@AfA?bBH`CEhAGN_@Vi@d@W\\a@t@]lAMfAY`BAj@@bCZxIFfANlEDj@PvAL`B\\jCJp@Db@@p@Ap@a@tBk@lAeAzAkAz@u@d@UJ_@DQ?o@OiA_@eAQ}Am@m@e@e@IWKOBq@Ze@d@MXCXExB@zEE~BGfHCr@AhHGj@KfBIZYv@w@nAQb@e@z@sAvDKd@cAdD[v@Yf@g@|AYl@ATA\\DXlAvCl@vBTxAFv@AXO`@_A|Ae@^y@Zq@h@i@d@[v@_@`Cy@hCO|@Gx@Cl@@p@HlBAjAG~@It@HfABp@KjCD`@^dBLbAFdACv@St@GLMLwAl@u@RWRQ\\I^Kt@EfB@dBLlDUfAOXKBMAo@O",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3289349210",
    average_speed: 3.143,
    max_speed: 4.4,
    average_cadence: 87.4,
    has_heartrate: true,
    average_heartrate: 157.9,
    max_heartrate: 170,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 75.6,
    elev_low: 20.7,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Måndagsmilen",
    distance: 11325.5,
    moving_time: 4468,
    elapsed_time: 4991,
    total_elevation_gain: 210.1,
    type: "Run",
    workout_type: 2,
    id: 3088659568,
    external_id: "2020-02-10_18-50-36_4bd04ff0-a6cc-4557-af3a-e588f0d8454c.tcx",
    upload_id: 3297623845,
    start_date: "2020-02-10T17:13:11Z",
    start_date_local: "2020-02-10T18:13:11Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.716291, 12.004157],
    end_latlng: [57.716352, 12.00419],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.716291,
    start_longitude: 12.004157,
    achievement_count: 1,
    kudos_count: 4,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3088659568",
      summary_polyline:
        "yug_J}pghANNhAMXi@PSlDqB|AcB\\m@n@_Br@gA`@WFUl@c@l@s@pAOr@WjAB`AZdBPbCW|@LnAAv@WfAF`Di@x@b@vD^xDvAvF`Al@Tb@Mj@o@~Ac@Ti@Bg@YwJHMr@]Ls@AiCe@cQ?_FDuBV_FRI\\L\\c@@y@XYdACdDnBp@LxAg@z@@\\uAfAwAd@~AZz@Nt@d@pAFd@Vr@Jz@XpAT@jAoAXCDPb@f@?dAVz@t@`@d@~@VLZ?|@e@^i@t@[JSj@c@FUnA_AXkADa@Le@TBh@u@bEsAd@LjBLz@Oj@k@^QhBuC\\]PCp@HdBs@jAkAZn@FTF~AFT~@Px@Mr@l@hC~@dAI`@bAl@d@LXPHfBa@n@BXRb@DXMP]T?ZUVo@p@i@jAkAf@M`AGpADbA_@VWVi@f@WP_@f@k@FS^ULSLa@PmBNa@DYDiBPgAMsABkAL}@^_Az@oA`@a@l@mAz@aAl@}AXmAB[EoBOmAE{@GaFG{@CkAYgCe@kB{@eEIw@eA}Ci@yCu@wBcAwBi@m@K[aAsAk@a@gBYYJwAbBk@vAkCdCMf@Ah@_AxCG|AKf@Cf@Wh@e@Te@A}@h@c@C}@r@_@hACd@Q`@G^KTIFNhAKjAURy@QmANcA_@ODwCjN]G_A\\g@n@i@XwAKq@^MRKDu@[k@iAg@SaAUeA?aAMg@DsDe@x@eCr@kATSl@QlBkALWb@_@|A{@j@u@n@yA^e@@UM]{@_@OSKs@GaBMy@MQu@MWDu@|@a@Gk@h@_@h@cA`A}@rA}@XWl@WLa@p@i@JaAaAg@JUVOh@SXcBf@k@jAYRKh@Un@a@l@YIsBLy@u@u@`@]DGMIm@A}AYu@QKmATeB|@{AEe@v@_@XqB~BMHyBc@o@NkAAo@Qy@Bm@WeCOgAHeCn@GLDt@Vx@Dl@@b@Ip@DfAfAxMH`GCfDQb@a@b@UR[Dw@UiBiA}@QsAFUTUl@GlBU`DsBnQH`DRnCNj@@jAW`B@xALrBd@hEHlB?bCEpDEl@Ij@o@VwB?_CXgELyBEwALkBMoA^uAN_@ZM?[^aBfDg@xAa@p@q@n@sAz@cBj@STM^YRSBoA[",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3297623845",
    average_speed: 2.535,
    max_speed: 5.9,
    average_cadence: 81.3,
    has_heartrate: true,
    average_heartrate: 152.3,
    max_heartrate: 217,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 106.2,
    elev_low: 20.6,
    pr_count: 1,
    total_photo_count: 3,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 6449.5,
    moving_time: 2069,
    elapsed_time: 2085,
    total_elevation_gain: 111.2,
    type: "Run",
    workout_type: 0,
    id: 3090301322,
    external_id: "2020-02-11_11-41-24_a2a19608-0aa0-4800-aace-4be31cc9f890.tcx",
    upload_id: 3299457138,
    start_date: "2020-02-11T10:47:43Z",
    start_date_local: "2020-02-11T11:47:43Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.702774, 11.956649],
    end_latlng: [57.703079, 11.956997],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.702774,
    start_longitude: 11.956649,
    achievement_count: 3,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3090301322",
      summary_polyline:
        "iae_J_h~gA[a@BH@PAv@Nf@\\p@N\\J`@b@z@Zz@JJn@VNLPx@\\j@PH~@Pr@Xh@J\\NZTXZTJF?ZOH?JB`@\\HBXCdAPRHl@AH@p@b@d@NXV\\Jz@r@hA\\PPxAf@HFLTJLbB^VHV\\JHRBLDd@@PEVCVKBCLWHGh@K|@Cf@OTFTIRA@C@a@HIPAPE\\?n@I|@F`@EXHBGDWJG\\CXIZDPEZHz@Hh@Xn@HTLNLXj@J@R?TJNGTCFNFXHbAFTFHn@\\ZFbBn@n@Pl@Hz@?xA[pAa@VERIrAOf@Hf@TXFPJR?RH`@ERDZ@ZFd@ZvBtBTP`@Tb@FJBn@h@X^TRTh@Lb@Lv@NbBDN^\\f@R`@\\d@TNLt@r@\\b@Tb@Tt@P`ARpB?h@Kf@U\\s@^o@Lu@^qBdCUPe@?O^Md@Iz@Ab@CzBBrB?fBCd@@bAQz@m@dBMdAG|@?t@StCEnCGr@CnBGdBK`@c@bAGLQNYN]De@CS?iA]y@PYCYDq@?[IOA]Oa@e@a@USWm@c@SYk@i@a@k@]gBMa@GKe@c@a@o@KWa@{A[[OG{AMc@QQOSa@EOAQ?q@Ho@O}A@u@TwAXcATsAT_BJkACkAF_BE}BE]?k@Jg@Rg@j@s@TMTWFQDYAg@Iy@_AcEIMYWISI{@ScAW_@e@WmA[QDIC[e@Y_A_@aBMQ]_@EGSgBP_E?GMi@Dk@C[GMo@q@m@c@g@Im@C_@KQD}AFcAPc@@m@Hu@T_@AM@[L]F}@D_@DU?{@HYLa@\\_@PSPI@CYBYEOOYWYWCk@BUM]E{@Wi@Ym@Oa@Gs@[qBm@[Ce@SeA[iAi@eAy@o@YUOSI_@Cc@YOEMKOEQIeAy@uAuAY{@Iy@Uw@a@}@G]?i@I_@IQUEg@]]M",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3299457138",
    average_speed: 3.117,
    max_speed: 5.1,
    average_cadence: 87.2,
    has_heartrate: true,
    average_heartrate: 155.1,
    max_heartrate: 172,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 60.4,
    elev_low: 6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass",
    distance: 0,
    moving_time: 2719,
    elapsed_time: 2719,
    total_elevation_gain: 0,
    type: "WeightTraining",
    id: 3093141400,
    external_id: "2020-02-12_11-41-55_fc592a23-d46f-420f-aad1-fd9223714af0.tcx",
    upload_id: 3302602217,
    start_date: "2020-02-12T10:33:37Z",
    start_date_local: "2020-02-12T11:33:37Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3093141400",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: false,
    upload_id_str: "3302602217",
    average_speed: 0,
    max_speed: 0,
    has_heartrate: true,
    average_heartrate: 127.6,
    max_heartrate: 148,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5336.3,
    moving_time: 1530,
    elapsed_time: 1550,
    total_elevation_gain: 66.5,
    type: "Run",
    workout_type: null,
    id: 3098569137,
    external_id: "2020-02-14_11-16-55_7b10fa8c-8666-44f0-8dd6-62d435e1631a.tcx",
    upload_id: 3308652528,
    start_date: "2020-02-14T10:40:54Z",
    start_date_local: "2020-02-14T11:40:54Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.703123, 11.956891],
    end_latlng: [57.703055, 11.956969],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.703123,
    start_longitude: 11.956891,
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3098569137",
      summary_polyline:
        "oce_Jqi~gATGV?D@HNFZ@ZLb@Zl@h@jAl@v@Pd@rAvAz@h@d@p@Z\\TLdAZTNNPJDNGZFNTRL`@HZ?l@Vb@Tj@HVJn@f@p@TVNPDVPb@L`@PZHHDRXh@H\\AVHZ@PB\\Pv@JNJRXZn@LNf@FVAXDREJWHEXE`@FXATKr@Qd@QHMBKHQh@KRCtADr@E`@?XJD?PMf@KfAJRG^B^Gf@JRAp@Rd@Z`@DTRd@BBBDLLdBFVLNj@\\nA`@tAx@~@Rp@ENFNTTj@T|@Z|@rAnCl@fBx@zAd@j@h@\\l@XPLFNJf@\\b@Xv@R^v@dAj@nATp@PLj@Rb@Xz@fAf@f@V`@Zr@VXJDH?ZMPQXg@f@k@l@g@|@Y|AWRINSL_@Fc@Aq@IuAIu@o@wBq@gA[YWOcA_@UUe@CIKESDs@G_AO}@S{@M]OWWSOQiB_Aq@q@cAy@a@Gc@OwASaA[k@U}@SSC]@g@LO?_A\\Y@w@P}@Li@@eAM{@[a@Em@QYQm@MKEUSIKESEeAE_@OUi@e@MGQBm@`@[?}@MY?{Aa@[Bu@C_C`@{A^[?m@JuA^y@JW@sAZy@\\q@BYAcAMUO_@[QEe@QQQYOyAmAc@Ue@G_Ae@_@UaAc@WGs@[i@OUCu@Qa@QSW}@c@e@OOMWOSCYOOCWU_A[q@c@y@c@MMS_@c@_BWm@g@kBMm@Um@OWUWMMOG",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3308652528",
    average_speed: 3.488,
    max_speed: 5.9,
    average_cadence: 88.2,
    has_heartrate: true,
    average_heartrate: 160.5,
    max_heartrate: 184,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 33.9,
    elev_low: 6.1,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Backintervall",
    distance: 4418.3,
    moving_time: 1700,
    elapsed_time: 2036,
    total_elevation_gain: 49,
    type: "Run",
    workout_type: 3,
    id: 3105464585,
    external_id: "2020-02-16_16-07-07_60525960-524a-45f5-ad3c-3e172693d401.tcx",
    upload_id: 3316389275,
    start_date: "2020-02-16T14:57:35Z",
    start_date_local: "2020-02-16T15:57:35Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.716297, 12.00407],
    end_latlng: [57.71621, 12.003896],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.716297,
    start_longitude: 12.00407,
    achievement_count: 2,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3105464585",
      summary_polyline:
        "yug_JmpghAa@KIMYQKK[i@Q}@?YD_@Nm@BE@@JWDe@EeAWoBEiABiBH_B@_AIgCGo@WwEQkCAa@g@iG?y@DaALe@LAFBFHHTFDNGLYPq@f@uDdAcGTcAPa@tAwAj@g@dBoB|AsAdBkBp@k@FDL^b@n@Xf@b@fAh@lCF~AUdAO`@MPc@f@YPk@Va@X_@d@e@z@g@lCMf@a@nAQr@Gb@IxBHlB?pAGrAOpAHz@@r@ErBBj@ZpANpAHjACdAMj@MRi@Z[Ha@Fi@X[ZM\\ObAInBBjDB`Ba@dB?PFV?NYx@ANDRKFOAi@Wc@O?BWL]BMPSl@O\\]X[x@YTEHATFf@Nl@\\dABTYpAJSLk@AGESa@cAOq@AU@QNYHWBQAMGKQIq@e@QYKu@BoADGLG\\DHDRl@\\d@P\\HJFALYJKR?LC`@SCCBAQLSBKHGPIb@KTYRUp@KNWPGP?LTtA^bABL?LOn@Ef@LSDQDQ?Ms@mCCY@MXe@DYASIQ[Gg@]MOIOGUCYDsAFGTGL?NFVt@XZZh@DBDAL[HMf@MTSD?WFO?MJ]|@GXQPUr@]`@GN?TBP\\nARf@BRCXOv@AVPg@DW?KGU_@gAS}@@SPYNe@?SEIIIYMo@a@Qe@CW?]F{@FGLCR?JDJLPf@\\d@h@`ALF^FPHVVn@|@`@\\`@f@LJFBLCDEN}@?u@S}A?u@D_@Ai@We@[UUCYF",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3316389275",
    average_speed: 2.599,
    max_speed: 4.6,
    average_cadence: 83,
    has_heartrate: true,
    average_heartrate: 153.8,
    max_heartrate: 183,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 41.9,
    elev_low: 19.3,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Afternoon Run",
    distance: 10191.7,
    moving_time: 4047,
    elapsed_time: 4299,
    total_elevation_gain: 188.9,
    type: "Run",
    workout_type: 2,
    id: 3108745098,
    external_id: "2020-02-17_20-28-54_a0108383-b5cb-443d-906a-845b51d52699.tcx",
    upload_id: 3320081328,
    start_date: "2020-02-17T16:47:46Z",
    start_date_local: "2020-02-17T17:47:46Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715768, 12.004371],
    end_latlng: [57.716273, 12.025552],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715768,
    start_longitude: 12.004371,
    achievement_count: 1,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3108745098",
      summary_polyline:
        "org_JirghAVYt@Yx@m@x@]zAwAd@{@`@iAl@iAn@i@ASr@o@p@cA`AId@HTQVGj@V~@?lB\\rA?rAMnC@|Aa@^FzBa@v@j@jD|@~@F`@TdBf@tALn@VvBTt@T^Gl@u@zAi@L[Hw@SgF?mCf@_@VIJUDe@AwBa@iPC{CD{CPcFDm@FQRA\\RJIHSFECiAR]TQf@@`@f@t@^f@f@r@V`@ItAaATq@PWVELF\\d@AdBt@fCbAbGx@zDVTPDd@q@`BsABL?nACl@Vl@ZlARL`A?p@j@N\\PJb@Ip@o@r@Yf@s@ZS`@?r@_@f@Jp@Il@s@d@[FcAXcAHKz@YPWTKv@YR?HO`@Qd@_@T]TDTXRAn@[p@AXMTWhA]b@[\\o@nCy@DUNGJ[V[Da@f@QdBYz@p@rAd@RDb@SRBPPTj@f@d@JRLHr@QfBHd@VHLJB`@[T_@\\BVOZu@n@o@`@i@dAu@v@@XIdAN|@YX[\\q@\\Kx@q@Z{@XUZs@TaBL]F_@?sBL}@OwAFqAJs@Ts@`@u@nBeCn@s@f@eAb@{AJg@@qCY_FOyGSkB{@gE[gAa@cCw@mB]qA_@gCmBuHc@iA_@q@mA{@iAM[NQf@aAnAy@rBm@n@sBzAKj@Ch@UjAc@pAA~@SjACh@iAjAq@Dw@Ty@BYX[dAKl@Qj@Qf@IL?TLj@EdACLc@Pc@KyAFk@Mc@JQGy@J][MSGCO@]d@QBMKu@oA_@gBGMs@?i@VKAgAgAu@Ug@]IYOcA@_@Qa@Ki@OOMw@?q@I]]a@YK_BN[S[q@w@qDu@BWu@wA_Cc@wA]kBQe@iAU}A@q@PuA~@sA^y@JKa@OaC@o@JkAAe@g@qCW_AO]aAw@eAe@QCwAf@iBZm@By@]]A_@LiBpAUVw@Z]d@u@hBq@h@o@^SIeCwD_@o@Us@q@MUBQLQVYv@m@pAq@pCy@lCShBk@xDS`CMd@QJ]?g@jAkBjCmDxBgAVwAtDg@fAm@l@UJYd@SLIN_Ad@e@H_AUa@NUTE`@?vAEbAAbDGx@Br@AbDIPe@@wE_@_@QoBYo@Ys@KcDeAyFwAmC]",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3320081328",
    average_speed: 2.518,
    max_speed: 5.6,
    average_cadence: 80.2,
    has_heartrate: true,
    average_heartrate: 148.5,
    max_heartrate: 168,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 106.2,
    elev_low: 20.6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass ",
    distance: 0,
    moving_time: 2954,
    elapsed_time: 2954,
    total_elevation_gain: 0,
    type: "WeightTraining",
    id: 3113765071,
    external_id: "2020-02-19_15-29-09_150e6012-71f5-40bf-b8f9-bcf0ed3cd94f.tcx",
    upload_id: 3325709316,
    start_date: "2020-02-19T10:37:39Z",
    start_date_local: "2020-02-19T11:37:39Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3113765071",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: false,
    upload_id_str: "3325709316",
    average_speed: 0,
    max_speed: 0,
    has_heartrate: true,
    average_heartrate: 131.7,
    max_heartrate: 161,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5381.1,
    moving_time: 1540,
    elapsed_time: 1592,
    total_elevation_gain: 66.7,
    type: "Run",
    workout_type: null,
    id: 3116007404,
    external_id: "2020-02-20_11-12-10_553dd06b-3999-4879-bc2e-d055884de22f.tcx",
    upload_id: 3328205621,
    start_date: "2020-02-20T10:34:38Z",
    start_date_local: "2020-02-20T11:34:38Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.702801, 11.957267],
    end_latlng: [57.702922, 11.957005],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.702801,
    start_longitude: 11.957267,
    achievement_count: 2,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3116007404",
      summary_polyline:
        "oae_J{k~gACIFGRMNGS?ID?tAJr@Fr@LVZXRXf@h@Nf@Dt@N\\h@h@TXJFXH^Zl@r@XLRLZHRXNJTVHRZ^d@Tt@DTF^B`AXb@XTFNJ\\Fx@V^DNLN?ZVd@NT@\\RT@LBp@ZNBPJJBVTXLP@NHTDbBv@RBd@GJCHSl@On@IZMz@IR@TCDCHSb@K`@@PEP?hANz@BTCb@STC\\FTHd@Gh@Ff@AZF`@?l@Pb@Rh@GXDPELBHRRhBJXHHv@b@tDnA\\HT@l@ENFNLNVTj@Pv@Vv@Ll@N^`@l@LVVlAt@fBX`@h@h@lAj@NRLd@d@n@Rl@Vj@`BhC`@`AJFz@Np@\\dA~@r@vAHLLH\\J\\GVONQbAy@d@e@JEvB_@b@ULUL_@D[?]Gu@i@iCUo@m@_A{@w@u@]uA_@GOESCw@WiBS}@_@u@OQYe@gAm@i@c@sA{Ai@c@QK]Go@D]EwA[{@Uc@GwBPg@TYBm@To@Jy@F_AGSE_@Og@Kg@W{@Uo@[MMCIQiAYiAGMWSUGS@k@POTUNUHK@u@Wm@[eAOo@AKAECQc@GGICi@F{@RUJ[Dq@Xm@HSHu@RYNsATsA`@a@Hm@R[Fa@NW@c@OMOEMKIa@Qu@w@Ya@cAy@ME]E_Ag@OKYKWC[MAKMEISECu@CuAP_@Ee@Us@QSQYOIKQIE]EGwAS[CS@SGY?e@MWQc@IOSYu@c@k@Is@e@qAK]IQY]ISAWHgAOaAEMGIm@U",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3328205621",
    average_speed: 3.494,
    max_speed: 11.7,
    average_cadence: 88.3,
    has_heartrate: true,
    average_heartrate: 157.9,
    max_heartrate: 177,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 33.9,
    elev_low: 5.7,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Lunch Run",
    distance: 5999.1,
    moving_time: 1806,
    elapsed_time: 1860,
    total_elevation_gain: 103.6,
    type: "Run",
    workout_type: 0,
    id: 3118719610,
    external_id: "16A6523B-DB2B-4CBA-AF76-DF11029F7070-activity.fit",
    upload_id: 3331223605,
    start_date: "2020-02-21T10:40:07Z",
    start_date_local: "2020-02-21T11:40:07Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.703041, 11.957139],
    end_latlng: [57.702854, 11.957067],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.703041,
    start_longitude: 11.957139,
    achievement_count: 6,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3118719610",
      summary_polyline:
        "_ce_Jak~gABALHBG`@v@Nd@Fn@Nl@HP^`@^x@d@x@\\x@BLLJJNDDH?lA`@HFLBPLTZXBJHXNfAHL^DD`@PPRb@VTXp@N~@|@XTLBLPd@Xf@d@DAPVL@LHf@ADC\\Bf@PPLXF\\^RD@@LEvAJXNNTXRv@XRDb@?n@Ud@Gv@[VSh@Sr@ARBZ?^CVIb@AXIdA?REb@Ct@Hn@XJAZ@\\DR?l@P\\FZJDFn@N`A]JARFFEDBR@LHDH^@HEX[PKTGF@LVZ`@|@n@LPfAx@^p@X\\^`AXd@b@dBb@hAVx@n@~@VTNTNj@f@vAl@|@LDPLRFJNZXFNHZp@t@z@jBl@t@Vb@LDNPb@t@NHTCTHNALBLJZl@VZRj@HNRr@LbADl@Al@HtACx@@h@Aj@NrE?z@A^Eh@WjAO`Ae@nAQx@IdAG~ASvAG~@Gf@MpC?hAKb@KPg@~@KHOHO?OF_@?e@FIAc@KQC}Aa@a@@WK]CUKoA]UMqAcBQGiAu@Sc@Ka@Wq@_@w@WYa@y@ISIe@a@cAQ[IIOGc@KQMm@UMOGQEg@@}AJw@j@uCHO?C^q@R{@Rg@B_@Jk@JeA?cAJyBEwA@}@Hq@Dw@HULQN]RSP[La@AYOu@Us@EE[w@Q}@IUYa@UO}@KOMKm@IMG[Q_@U]GAYDIE]EWMOAQEQKG?QHKNKD]Ec@@KCOMMCWAQJc@GOHi@Ea@}@Ww@Sc@IWDG_@}@COPA[aAT?AQR?HCKk@BEEEBCMEMIYEEBUAK@EDQAOI?EECaA`@w@IMD]Mq@IGWIESAOHOC_@DSFQBI?]Dm@SK?m@]MHOT_At@GAUDEAGEUFGEs@EIGABOcAKSSO{@y@QM_Ac@m@SQK[IYWcAo@SEUMGJ@??QKi@IOMs@GKMi@EEKc@C@Oi@EEG?GKYu@EEKKE@W[k@SO?UUI@ECIMI?ED]EQK]KEGi@kAm@k@cAeBq@_BQUI]WaB[m@",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3331223605",
    average_speed: 3.322,
    max_speed: 7.2,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 60.4,
    elev_low: 6.4,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Afternoon Run",
    distance: 11512.8,
    moving_time: 4541,
    elapsed_time: 5203,
    total_elevation_gain: 202.1,
    type: "Run",
    workout_type: 2,
    id: 3128705784,
    external_id: "2020-02-24_18-39-18_49ee4a0f-ab43-47da-818f-59f50e32c2b6.tcx",
    upload_id: 3342329021,
    start_date: "2020-02-24T16:53:19Z",
    start_date_local: "2020-02-24T17:53:19Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715837, 12.004363],
    end_latlng: [57.716301, 12.004024],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715837,
    start_longitude: 12.004363,
    achievement_count: 1,
    kudos_count: 4,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3128705784",
      summary_polyline:
        "}rg_JgrghATUp@MtBoAh@i@r@cAjAyCZg@f@o@bAOn@g@f@PjBK~B`@vA^x@]h@AlBu@xBLzBF~A[h@o@LCV^tAHp@LfAZdBWvBd@VCv@z@n@^bBb@f@@NM\\s@~Ag@Te@Bk@GcC[oFBMFGdAWDaASkFBYA_BSuMBeCTeGHOh@GnB{CL@xBrAxAp@\\IdA{@LQNk@RWPCZPFPC|@@`@zBhKv@dEf@Tj@o@rAcAF?@x@HnAhAdCr@~CbAhAbAXHGE_AbAaAHe@LOHm@To@NO^}@RKLU^Qb@w@ToB@}@HWbAmAN[TI\\e@b@wALUb@G`@c@NElAAxAZj@OPWdA}@z@gBVc@ZUlAL^I\\Yd@Ih@{@HA|@r@H\\JdALTnANn@Oj@^p@NhAh@XBd@OXTVv@`@ZJRFVTB^UbAKd@Bb@RXAXSVi@VDZOj@gANE|@gAj@Wd@@t@CbAJh@U^[`@i@l@Up@{@Le@`@KTs@PSN_BR}@?kBJmAIeBL}ALo@^_A|DkFf@oA`@{ADm@AqAYyCG_B@_BOuD]aDcAqFQo@K{@gAoDuAwGmBgH_@_@m@UkDe@{AKMu@a@gAu@s@e@KWFa@n@q@p@gA~@o@T{BhBwAp@c@A][i@oA_@sAGIg@By@d@a@bAgAvFkA`EmA~FQj@qBbE}A~AmBQm@c@Sg@E]LwACk@I]g@Mk@Bo@h@[f@c@Du@r@w@pA]Rm@dAcA\\]r@_@\\Yb@k@Fs@kAUAg@Ra@~@WXeAb@c@^]x@WNOfAOXCTORa@IkB@s@m@WMQBg@`@O@Oe@Gg@?w@Kw@Yg@[FeCjAoBCq@w@q@{Am@WWFcAvAm@v@_@PqATw@g@{@{@Oq@MwCMYc@k@g@sA[[_AKi@_A_Cl@yAPw@_@g@IuCR_AMcBi@g@?IJ{ApE]h@SNg@Jw@z@a@ZsAVi@Oc@F]TC`@Bf@EfA?nKBx@Fj@@fBHhAn@zD|ArM`B~LdBzGh@bBTbAz@jCJn@`@nL\\~ETnG?|BGbB?pDINSFWXWH{DTm@Z{Cd@a@ScEAoBSuAHo@Pk@Aa@TcBdBqA~DW`@sAbAaExBk@z@aBJ",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3342329021",
    average_speed: 2.535,
    max_speed: 4.5,
    average_cadence: 80,
    has_heartrate: true,
    average_heartrate: 145.7,
    max_heartrate: 169,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 96.1,
    elev_low: 20.6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass",
    distance: 0,
    moving_time: 3407,
    elapsed_time: 3407,
    total_elevation_gain: 0,
    type: "WeightTraining",
    id: 3133307406,
    external_id: "2020-02-26_11-47-37_2048990e-66f5-490e-8297-a51b2634dff2.tcx",
    upload_id: 3347419976,
    start_date: "2020-02-26T10:28:44Z",
    start_date_local: "2020-02-26T11:28:44Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3133307406",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: false,
    upload_id_str: "3347419976",
    average_speed: 0,
    max_speed: 0,
    has_heartrate: true,
    average_heartrate: 125.1,
    max_heartrate: 159,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Backintervall",
    distance: 3578.6,
    moving_time: 1411,
    elapsed_time: 1651,
    total_elevation_gain: 58.4,
    type: "Run",
    workout_type: 3,
    id: 3135996852,
    external_id: "2020-02-27_11-54-40_c8dc1a03-df2c-4459-92b9-337568514ff7.tcx",
    upload_id: 3350414088,
    start_date: "2020-02-27T11:19:15Z",
    start_date_local: "2020-02-27T12:19:15Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.702631, 11.956137],
    end_latlng: [57.7038, 11.957116],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.702631,
    start_longitude: 11.956137,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3135996852",
      summary_polyline:
        "m`e_Jyd~gAE_@ImAGO_@[W@i@O_@DQGGGOYIm@O_@yAmAWg@OOUk@]e@CG@I`@~@`@`@B@T?JC\\\\BHBVHN?j@DP?Jp@n@TN\\B`@G`@@TRXl@N`@DbADf@GFG??y@YaBMG_@C[K_@BQMSc@Uw@KSGIYKk@o@U[e@{@g@oAXt@VZPXHFR?FC@BLb@LRJb@?XEPFLb@b@^Tp@FPJTBNLX^NJRn@JbAAFCBQsAOi@Aa@_@Oc@MWAWDKCOg@Kw@OQQIUM{@w@kAwBAWPZTTd@r@LBNC?HXh@F`@Eb@F^dAp@j@NR@TJRP^f@PXT~@Hd@?JEDAAOe@Ei@KYKg@y@m@K?YFKCWw@Ig@SUq@c@o@q@eAqBSY?EPf@T^JHP\\HB@DX?HE@GB\\d@r@@VM^BHNVRPRH^@b@F\\AZZXh@\\bABhAAAE@GAImAAIOWGc@SSYIKII?YLSGIKk@mBgBcBUe@_@k@Uq@`@n@f@lARHTMDIDXNXLJBNDBHWHkBHu@B_AAo@Ig@Mg@i@oAi@aAOGU?SEw@j@S`@c@@MEMOIWAk@B_BIw@IMKEcALGFKTIh@U~CMd@Eb@?p@HJPF\\^h@^fAzALZ@z@Pp@JJT?BDLDp@n@Ld@h@nAZ`ADCJSRc@RS",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g4836285",
    from_accepted_tag: false,
    upload_id_str: "3350414088",
    average_speed: 2.536,
    max_speed: 5.3,
    average_cadence: 79.3,
    has_heartrate: true,
    average_heartrate: 143.8,
    max_heartrate: 179,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 26.9,
    elev_low: 7.3,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Bohusleden: Jonserd — Angered (Etapp 5)",
    distance: 15928.7,
    moving_time: 6868,
    elapsed_time: 9165,
    total_elevation_gain: 395.5,
    type: "Run",
    workout_type: 2,
    id: 3141622894,
    external_id: "2020-02-29_13-21-55_1dc0994d-d991-497e-81d1-f316b189c084.tcx",
    upload_id: 3356655100,
    start_date: "2020-02-29T10:22:38Z",
    start_date_local: "2020-02-29T11:22:38Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.75052, 12.175358],
    end_latlng: [57.796, 12.052005],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.75052,
    start_longitude: 12.175358,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3141622894",
      summary_polyline:
        "wkn_J}~hiAqA{D[IyAwAqAmBYGq@yAkAwG}@mK[oBC}ALaCzAMh@m@r@Pd@Yl@k@J}ARm@Iu@UKY_A[Q}@KgBjA]m@GyE\\_@z@Kt@yBGwAIDIlAk@UsBqBsEkCYg@@Oc@k@QuA\\gBLoC{@uLFa@o@}AcAHqBrAu@AsA_COcBY]{Ay@oAK{@s@o@Im@_Ae@M}BpBoC|AeBrCi@f@NnBWrEHj@lBpBz@nDnA@p@nATz@dAl@iBgBk@oA}AoAa@gAwAcBq@Ky@jAi@tA]|A}@bLs@nE\\dBE`In@dBgBZJmF`@gADqAWyAg@Mq@t@W|B}AjDaB~AcBlC_Cr@Q`@GhDy@bAaBvDo@rCm@dB[VAlA{Bl@cAp@eC^[jCYx@qAt@UlAiAz@cA~CyAbBcBfAwAzA_@vBeBhBo@zCq@dBMdA^~BRvGuAvCEh@q@dA_@Ac@d@g@jA_@nBOzFf@`Fv@|EDrBa@dAu@T]h@C~Ay@pFBhBfAxD\\n@@t@}@dBGj@BdBe@jCgAfAe@pA}Ax@QdAH|INZz@nFx@t@p@LdAbAl@|Bd@dABv@a@tDLxE{BrDeAl@StADz@XnAKhANz@O`BHlBJhAd@z@Jn@?`D`@zC[zC`@`EkAnF@dHfB`Mb@r@NjBz@`E~@`CNbE[nCo@zAGv@cA`BgAt@T`IPjBjBhBhA`GbAdCdFdHHPaAaAlBrC`AjDh@|HnE|IbAjAt@`DCtBi@lBiE`CiA|B[Mk@b@wBpDo@TqArBm@\\WfAoAZe@r@Ad@mBTsD`FcAVy@aE[McCl@}DxD{@_@i@gAgAQA~@`@rACr@z@`Bb@VVvBq@|Bq@|@kBrFk@bAIjAy@lCi@r@s@fBs@Mi@TyAfBUd@ObAi@fAkDfEOn@w@r@gFnIuF`EsAh@_AtBqA~AkDLmCbBwAyDy@yKGa@OI{@n@aCnEwE`G?p@nAdD@bA{A`Ak@lACnBg@jHPzHOrG^zGJpGN`Bn@fCNxAo@|Fq@fDmAtCuB|C]hAQjBEtJ_@~DT`Fe@lEtBrIJvBGnD]hCuAhEu@pDkAnOKpOaA|B]dBDVXV`Cb@MfBGhFc@~AcBlBa@fAKrBw@~FJrAn@rCOfAkBvC{@x@}BbA{A@{BzBc@xBy@vHuBpI",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3356655100",
    average_speed: 2.319,
    max_speed: 3.9,
    average_cadence: 79.7,
    has_heartrate: true,
    average_heartrate: 146.6,
    max_heartrate: 170,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 139,
    elev_low: 26.9,
    pr_count: 0,
    total_photo_count: 4,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Måndagsmilen",
    distance: 10325.7,
    moving_time: 3927,
    elapsed_time: 3964,
    total_elevation_gain: 173,
    type: "Run",
    workout_type: 2,
    id: 3148278690,
    external_id: "2020-03-02_18-10-46_4ece9ff5-75d2-459f-98c2-0fd2ea7e2938.tcx",
    upload_id: 3364110670,
    start_date: "2020-03-02T16:47:28Z",
    start_date_local: "2020-03-02T17:47:28Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: [57.715515, 12.004371],
    end_latlng: [57.716193, 12.004063],
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: 57.715515,
    start_longitude: 12.004371,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 2,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a3148278690",
      summary_polyline:
        "}pg_JirghAFWVWdAe@`Aw@tAcB|@_AdBkDb@sA`Am@f@EhB^lDPVAf@[t@Ht@Wt@@vB]dERp@ZlEVzBEnCd@n@XhAx@pAf@VK^[h@w@hAUb@[J_@@k@OiIBKr@c@Jk@MsIWcIAsCG}A\\aJx@G@{AHw@LOb@?|A\\rAl@t@Nl@\\lA]Z[b@{@x@y@Pg@|AeCT}@^o@f@mBJs@Tm@j@q@f@Ft@a@dA_@bAmCRw@De@Ca@Q}@Cw@PuECeABiAO{Cg@uD\\_BDq@`@m@N}@h@c@j@SX]Pg@x@u@b@?`@`@f@L|@_@Zs@~@YZSb@k@r@m@Rc@r@_Aj@Gv@cA|@y@R]Hw@GWIMc@OwAA]Sa@}Aa@sBA_@p@u@jAu@h@u@f@cB`@_Ad@c@PYRs@HoBDQz@QJQDg@Aq@BO`A]`@g@z@m@P[F]?m@GoBGYa@m@CKv@{BDe@m@oCP}@AOKa@]q@QuAMcBDyA\\_At@}@r@uAVcBNe@Jk@Pc@PqA`@o@`@mAPyAHYJiARs@Rg@h@q@v@oBRK`@o@n@q@\\OBQAY[GWoAA[M[g@OUu@WYa@?SFSRO@c@NYZe@XSA_BtAq@RMPc@R_BlBcBhAUf@Gn@K?YVaBpCa@VWb@Uj@c@pCYfAQfAu@z@U`@]jAKbAk@lBA^Hb@FhA}@tCKh@C~@@bGT~C?j@SfAgBjDMh@?l@|@dKRtA`@tAEhAMp@BPCJYEg@Tk@@wBz@o@d@cAlAy@l@kBPYH[Z_@Ik@\\YBu@d@s@z@]v@MNaAbCOt@]PQb@a@Xa@v@O?IHKn@[j@Gv@g@vAwArBo@p@e@Lg@?wAM{BYa@DcCc@cABuAMgBb@c@ZEV@r@RdADt@Kx@@h@`@tFf@`EDjBLlAA`BIdA?pBMj@_@h@[Tc@HuBkAo@UuAOc@L]f@M^C^AjBQhAcBtPWbB`@hGH|DZrEZ`H@bACvAM`BDpCEPo@`ACj@iAViCEu@RaAS]Tk@Pm@MyBJaDMu@BeAX}@EYNYn@YXy@hBo@hA[~@WZyDxBqA`@aAlA]Lk@E",
      resource_state: 2
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g2725420",
    from_accepted_tag: false,
    upload_id_str: "3364110670",
    average_speed: 2.629,
    max_speed: 4.9,
    average_cadence: 81.4,
    has_heartrate: true,
    average_heartrate: 151.9,
    max_heartrate: 173,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 97.7,
    elev_low: 20.6,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  },
  {
    resource_state: 2,
    athlete: {
      id: 19649721,
      resource_state: 1
    },
    name: "Skivstångspass ",
    distance: 0,
    moving_time: 3171,
    elapsed_time: 3171,
    total_elevation_gain: 0,
    type: "WeightTraining",
    id: 3153124831,
    external_id: "2020-03-04_11-52-05_3fa2502c-afb2-4db2-846a-96f67e76627b.tcx",
    upload_id: 3369492377,
    start_date: "2020-03-04T10:32:10Z",
    start_date_local: "2020-03-04T11:32:10Z",
    timezone: "(GMT+01:00) Europe/Stockholm",
    utc_offset: 3600,
    start_latlng: null,
    end_latlng: null,
    location_city: null,
    location_state: null,
    location_country: "",
    start_latitude: null,
    start_longitude: null,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a3153124831",
      summary_polyline: null,
      resource_state: 2
    },
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    from_accepted_tag: false,
    upload_id_str: "3369492377",
    average_speed: 0,
    max_speed: 0,
    has_heartrate: true,
    average_heartrate: 134.7,
    max_heartrate: 165,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false
  }
];
